# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d201aae6b5c7c38fbb9d0ec97a6039e0188a2b7b9ebce24e1b5ed242812ef02045c5120d00dc4ef8cf19619d03ddab7f65a37bb5db3eb759430a0b47dcc6687a

test:
  secret_key_base: d3ec8fb079fed42d98e89a883ddba679b65a567582fd8f45a9218bddf2908fb2ef66b2852abe8ff800de995a7d27d5a0dd308211a99f18b9a3c7ab4e49d0c4db

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
